version: '5.1.4'
services:
  playwright-test:
    image: pw-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run test:${TEST_NAME}
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results